# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required
rust: nightly

env:
  global:
    # TODO Update this to match the name of your project.
    - CRATE_NAME=v

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu

before_install:
  - set -e
  - rustup self update
  - sudo apt install -y libssl-dev

addons:
  apt:
    update: true

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: IuvroqqTuJR78Svgja/geHqYPd1JmAtdArBL+QGzDBPQ3BwULQPg9WZc9sHwBD+F+6ZovP/1ABQqrgIacsyjUWupL949OL7AZ+SJV3Awy7L/LDkHUrLQZozCG5a3LUDGQKmINfRpYcd1WeJmgP7DySugxmm5c/T9dgQ0EM8pLtssdf5fb6/HM+TeETNSF28MEzfj62cT7LwCGFWNN/vkR/hVoTikipy/3JnAWkrj4XWP6vbfmVjYEazLK85bfw3qD2LBinDmV2HMDVfv++aYyjCmnlWs6nf6Rc+TYtRB2cDtCH/XsCNQwVLSE/ZDaEatWIv2EiqrHLJcs1PGYd0eG6Cb0cM9fMucF/Xm8rlZ2ouJArVQEp7ClR27x+OW8PhLdHMR6DXOsTGUMCMG9db9j2fCv6LK+iOyTcFlbJkJ1X5Zfwee6MCSH9dFhz82xZIH0hDtYpl4dNy1vE/6z+vQ9nJYOCzrjIVA3LhMEdaOHZufMUhxNPvBC23Od2zc5f/li9xHEy+jEDqlCTgaWTD/vmg3K1cfuwoJ+mUFVC+a7LdU4MUWTQeoI1htlelYIw/hBI46i9WUD6a7rUMyJXpmTLUHSS23qPlKcfZ8d4XeS1BZ0dahWKcIFqaFHU0YX/jkDGscUQ0rcALBCuTxipcRdk6gr4nE6ikKSTdmdwEgmxE=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    tags: true
    repo: Chronophylos/v
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
