name: Build
on:
    push:
        branches:
            - master
        tags:
            - 'v*'
jobs:
    linux:
        runs-on: ubuntu-latest
        steps:
            - uses: hecrj/setup-rust-action@v1
            - name: Install cargo-deb
              run: cargo install cargo-deb
            - uses: actions/checkout@master
            - name: Build all binaries
              run: cargo build --verbose --release --bins
            - name: Archive binary
              uses: actions/upload-artifact@v1
              with:
                  name: v-server-x86_64-unknown-linux-gnu
                  path: target/release/v-server
    additional-files:
        runs-on: ubuntu-latest
            steps:
            - name: Pack additional files
              run: tar -czvf v-assets.tgz assets templates
            - name: Archive additional files
              uses: actions/upload-artifact@v1
              with:
                  name: v-assets
                  path: v-assets.tar
